# Generated by Django 3.2 on 2021-10-13 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='Corrans',
            new_name='Answer',
        ),
    ]
